#!/bin/bash

#
# Traq Packager
# Copyright (c) 2012-2014 J. Polgar
#

# Clone traq
git clone git://github.com/nirix/traq.git upload
cd upload

# Checkout version
git checkout $1

# Setup framework
git submodule init
git submodule update

# Pack it
cd ..
packmule pack --version $1

# Cleanup
rm -rf upload

# Move files
mv traq-$1.tar.gz pkg/
mv traq-$1.zip pkg/
